source 'http://rubygems.org'
gem 'rake'
gem 'ffi'
gem 'excel_to_code', '0.2.1'
# gem 'excel_to_code', git: "/Users/tamc/Documents/github/excel_to_code", branch: 'fewerSaveLoads'
gem 'minitest'
gem 'pry'
gem 'pry-rescue'
gem 'pry-stack_explorer'
